Avatar API/Controllers/Donation/DonationController.cs
using Avatar_API.Data.Services;
using Avatar_API.Filter;
using Avatar_API.Session;
using Microsoft.AspNetCore.Mvc;

namespace Avatar_API.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    public class DonationController : Controller
    {
        private readonly PackageService _cashPackageService;
        private readonly SessionHandler _sessionHandler;

        public DonationController(PackageService cashPackageService,
                                  SessionHandler sessionHandler)
        {
            _sessionHandler = sessionHandler;
            _cashPackageService = cashPackageService;

        }

        public IActionResult Index()
        {
            ViewBag.Currency = _cashPackageService.GetCurrency();
            ViewData.Model = _cashPackageService.GetPackages();
            return View();
        }

        public IActionResult Gateway(int price)
        {
            ViewBag.Price = price;
            return View();
        }

        public IActionResult Success()
        {
            return View("Success");
        }

        public IActionResult Invalid()
        {
            return View("Invalid");
        }
    }
}

Avatar API/Views/Shared/Failure.cshtml
@{
    ViewData["Title"] = "Failure";
    Layout = "_Layout";
}

<link rel="stylesheet" href="~/css/error.css">

<div class="error-message">
    <i class="fas fa-exclamation-triangle"></i>
    <h2 class="text-center text-danger">Your payment failed!</h2>
</div>

Avatar API/Views/Shared/Invalid.cshtml
@{
    ViewData["Title"] = "Failure";
    Layout = "_Layout";
}

<link rel="stylesheet" href="~/css/error.css">

<div class="error-message">
    <i class="fas fa-exclamation-triangle"></i>
    <h2 class="text-center text-danger">Your request is invalid!</h2>
</div>

Avatar API/Views/Shared/Success.cshtml
@{
    ViewData["Title"] = "Success";
    Layout = "_Layout";
}
    <link rel="stylesheet" href="~/css/success.css">

    <div class="success-message">
        <i class="fas fa-check-circle"></i>
        <h2 class="text-center text-success">Your payment was successful!</h2>
    </div>

Avatar API/Views/Shared/_DonationPackage.cshtml
@using Avatar_API.Data.Models 
@model DonationPackage

<div class="card">
    <div class="card-body">
        <p class="card-text">@Model.Amount cash</p>
        <p class="card-text">@Model.Price @ViewBag.Currency</p>
        <a href=@Url.Action("Gateway", "Donation", new { price = Model.Price})>Proceed</a>
    </div>
</div>  

Avatar API/Views/Shared/_Layout.cshtml
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto">
    <script src="~/lib/jquery/jquery-3.5.1.min.js"></script>
</head>


<body>
    @RenderBody()
</body>

<environment names="Development">
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</environment>
<environment names="Staging,Production">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"
            asp-fallback-src="~/lib/jquery-validation/dist/jquery.validate.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.validator"
            crossorigin="anonymous"
            integrity="sha384-rZfj/ogBloos6wzLGpPkkOr/gpkBNLZ6b6yLy4o+ok+t/SAKlL5mvXLr0OXNi1Hp">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.9/jquery.validate.unobtrusive.min.js"
            asp-fallback-src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive"
            crossorigin="anonymous"
            integrity="sha384-ifv0TYDWxBHzvAk2Z0n8R434FL1Rlv/Av18DXE43N/1rvHyOG4izKst0f2iSLdds">
    </script>
</environment>